"""EVERY prompt is his to change, and every change reaches the model.

WHY THIS FILE EXISTS, IN CHRIS'S WORDS: *"bro almost every prompt is uneditable! for
example the tutor might have core teaching ideas which claude cannot even imagine ...
right now he cannot inject those ideas in his creating curriculum prompts."*

He is right, and the design that shipped contradicted its own spec, which says in as
many words: *"'Locked' must mean 'an editor can't break it by accident', not 'Chris
can't change it'."* The lock was built to protect him from an ACCIDENT. It was never
meant to stop the owner of the app from putting his own teaching expertise into it,
and "the tutor has core teaching ideas Claude cannot imagine" is precisely the case
the implementation failed to serve.

THE TEST THAT MATTERS IS `test_every_slice_override_actually_reaches_the_builder`.
Everything else is plumbing around it. P2 put it best and it is worth repeating: a
Settings page that stores an override the model never receives is not a feature with a
bug in it — it is a screen that tells the tutor he changed how his lessons are written
when he did not. A textarea that silently does nothing is worse than no textarea,
because the tutor stops looking for the reason his ideas are not showing up.

The property is structural rather than asserted per prompt: the registry's builders ARE
the live builders (P1 enforces that with `source_of_truth` `is`-tests and the call-site
completeness test), so a render that honours an override is a live path that honours it.
What a render CANNOT prove is that the live CALL SITE hands the builder a resolution
source at all — so that is tested separately, per flow, in
`test_prompts_live_paths.py`.
"""
from __future__ import annotations

import pytest

from app.prompts import registry

# The two prompts that are NOT authored text and therefore cannot honestly be
# handed to a textarea. Named here rather than derived, because this list is a
# CLAIM that must be argued and re-argued, not a fact to be computed:
#
#   tools.descriptions      — `json.dumps(_tool_schemas())`. Generated from the 21
#                             entries in `agent/tools.py`. There is no prose to edit:
#                             it is the tool list serialised. Editing it would mean
#                             editing a JSON schema in a textarea and having the
#                             model call a tool that does not exist.
#   tools.system_claude_cli — generated by the PROVIDER BRIDGE
#                             (`llm/claude_cli._tool_system_prompt`) from that same
#                             tool list, and it vanishes entirely the day the real
#                             API key is used. Overriding it would let him edit a
#                             string that is a serialization detail of one provider.
#
# Both remain VISIBLE. Read-only and honest beats editable and fake.
GENERATED_NOT_AUTHORED = {"tools.descriptions", "tools.system_claude_cli"}

SENTINEL = "ΤΟ ΔΙΚΟ ΜΟΥ ΚΕΙΜΕΝΟ ΕΔΩ"

# The prompts whose LANGUAGE the course decides, not the cockpit. Derived from the
# registry so a sixth one cannot be added without inheriting these tests.
COURSE_LANGUAGE_PROMPTS = sorted(
    p for p, e in registry.REGISTRY.items() if e.language_from_course
)


def _editable_prompt_ids() -> list[str]:
    return [p for p in registry.REGISTRY if p not in GENERATED_NOT_AUTHORED]


# ---------------------------------------------------------------------------
# Coverage: he can reach every prompt that is ours to change
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("prompt_id", _editable_prompt_ids())
def test_every_prompt_we_author_has_something_he_can_edit(prompt_id):
    """The headline requirement. A prompt whose text this app wrote is a prompt its
    owner can rewrite — that is the whole of Chris's ask."""
    entry = registry.REGISTRY[prompt_id]
    assert entry.slices, (
        f"{prompt_id} has no editable slice. Either wire its text through "
        f"`overrides.resolve` or add it to GENERATED_NOT_AUTHORED with a reason — "
        f"silently read-only is the one option that is not available."
    )


@pytest.mark.parametrize("prompt_id", sorted(GENERATED_NOT_AUTHORED))
def test_the_generated_prompts_are_read_only_and_that_is_honest(prompt_id):
    """These two are machine-generated from the tool registry. A textarea over them
    would be a lie of a different shape from the one this task is fixing."""
    assert registry.REGISTRY[prompt_id].slices == ()


# ---------------------------------------------------------------------------
# THE ONE THAT MATTERS: his text reaches the builder the live path calls
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("slice_id", sorted(registry.SLICES))
def test_every_slice_override_actually_reaches_the_builder(db, slice_id):
    """Save an override -> the OWNING prompt renders HIS text.

    The override wraps the default rather than replacing it outright, so that every
    `{placeholder}` the builder requires survives `validate` — this test is about
    whether his edit is USED, not about the validator, which has its own tests.
    """
    from app.prompts import overrides

    entry, sl = registry.SLICES[slice_id]
    overrides.save(db, slice_id, f"{SENTINEL}\n{sl.default}")

    rendered = entry.render("el", db).text
    assert SENTINEL in rendered, (
        f"{slice_id}: he saved an override and {entry.id} still renders without it. "
        f"The builder is not reading `resolve()`."
    )


@pytest.mark.parametrize("slice_id", sorted(registry.SLICES))
def test_resetting_a_slice_puts_the_code_default_back(db, slice_id):
    from app.prompts import overrides

    entry, sl = registry.SLICES[slice_id]
    before = entry.render("el", db).text

    overrides.save(db, slice_id, f"{SENTINEL}\n{sl.default}")
    assert SENTINEL in entry.render("el", db).text

    overrides.reset(db, slice_id)
    assert entry.render("el", db).text == before, (
        f"{slice_id}: Reset did not restore byte-for-byte what the code says."
    )


@pytest.mark.parametrize("slice_id", sorted(registry.SLICES))
def test_he_can_always_save_an_edit_of_the_slice_s_own_default(db, slice_id):
    """The ceiling must leave room for the text it is a ceiling on.

    A `max_chars` below `len(default)` is a slice he can READ and can never SAVE: he
    opens the textarea, changes one word, presses Save, and is told his text is too
    long — about text the app itself wrote. The failure would look like a validator
    working correctly.
    """
    from app.prompts import overrides

    _entry, sl = registry.SLICES[slice_id]
    edited = f"{sl.default}\n{SENTINEL}"
    assert len(edited) <= sl.max_chars, (
        f"{slice_id}: default is {len(sl.default)} chars but max_chars is "
        f"{sl.max_chars} — he cannot save his own prompt back."
    )
    overrides.validate(edited, default=sl.default, max_chars=sl.max_chars)


@pytest.mark.parametrize("slice_id", sorted(registry.SLICES))
def test_a_slice_default_is_the_live_constant_not_a_copy(slice_id):
    """`is`, not `==`. Equality passes against a copy that has since drifted, which is
    the only case anyone cares about — same rule P1 set for `source_of_truth`."""
    _entry, sl = registry.SLICES[slice_id]
    assert isinstance(sl.default, str)
    assert sl.default, f"{slice_id} has an empty default"


# ---------------------------------------------------------------------------
# CHANGE 3: the preview must not claim a language the model is not told
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("prompt_id", COURSE_LANGUAGE_PROMPTS)
def test_the_curriculum_preview_does_not_follow_the_cockpit_locale(prompt_id):
    """Chris spotted this from the screen, and it was real:

        PREVIEW   (X-App-Locale: el):  "write everything you produce in Greek (el)"
        REAL CALL (a course whose language is 'en'): "...in English (en)"

    The registry rendered these with `language=locale` — the SETTINGS PAGE's locale.
    The live path passes the COURSE's language, which comes from the STUDENT
    (`interview.py:311`). So flipping the cockpit to English used to flip this preview
    to English while a Greek student's course stayed Greek: a screen presenting a value
    it does not own as one it does.

    In his live DB, 5 of 6 courses are `en` and 131 of 155 lessons are English. The
    engine is right. This is the viewer being made to stop arguing with it.
    """
    from app.prompts import registry

    el = registry.render(prompt_id, "el").text
    en = registry.render(prompt_id, "en").text
    assert el == en, (
        f"{prompt_id} still changes with the cockpit locale. Its language belongs to "
        f"the course, and no control on the Settings page moves it."
    )


@pytest.mark.parametrize("prompt_id", COURSE_LANGUAGE_PROMPTS)
def test_the_language_span_says_where_the_language_actually_comes_from(prompt_id):
    """The ORIGIN is the surprising part, and it is exactly what he asked about — so
    it is on the chip, not in a footnote."""
    from app.prompts import registry

    spans = registry.render(prompt_id, "el").spans
    lang = [s for s in spans if s.name in ("language_directive", "answer_in")]
    assert lang, f"{prompt_id} interpolates a language directive but marks no span"
    assert any("μαθητή" in s.label_el for s in lang), (
        f"{prompt_id}: the language span must name its origin — the student's/course's "
        f"language — because that is the fact he could not have guessed from the screen."
    )


def test_he_can_preview_a_course_prompt_in_either_language():
    """The honest third option: he does not have to take our word for the origin — he
    can look at both. `?course_language=` is what the card's toggle calls."""
    from app.prompts import registry

    greek = registry.render("curriculum.outline", "el", None, "el").text
    english = registry.render("curriculum.outline", "el", None, "en").text
    assert "in Greek (el)" in greek
    assert "in English (en)" in english


@pytest.mark.parametrize("prompt_id_ui", ["chat.system", "retrieval.grounded", "artifacts.generate", "lesson.from_selection"])
def test_the_cockpit_locale_still_drives_the_prompts_it_actually_drives(prompt_id_ui):
    """The other half, and the reason this is not a blanket change: chat, retrieval,
    artifacts and lesson-from-selection DO take the cockpit locale on the live path
    (`lessons/draft.py`'s own docstring: "the tutor's UI locale, threaded all the way
    from the browser's X-App-Locale"). Freezing those would be the same bug, mirrored."""
    from app.prompts import registry

    el = registry.render(prompt_id_ui, "el").text
    en = registry.render(prompt_id_ui, "en").text
    assert el != en, (
        f"{prompt_id_ui} takes the cockpit locale on the live path, so the preview "
        f"must follow it."
    )
