#!/usr/bin/env bash
# Build apps/web and assemble the Next standalone tree into resources/web/,
# exactly like apps/web/Dockerfile's runner stage:
#   .next/standalone/*  →  resources/web/          (server.js + pruned node_modules)
#   .next/static        →  resources/web/.next/static
#   public              →  resources/web/public
#
# NEXT_PUBLIC_AUTH_ENABLED=0: the desktop app is single-user on localhost; the
# API runs with AUTH_ENABLED=0 too. NEXT_PUBLIC_API_BASE stays UNSET — lib/api.ts
# derives localhost:8791 from the browser origin (the bundle topology).
#
# Usage: TARGET=darwin-arm64 ./stage-web.sh   (TARGET accepted for symmetry;
# the web build is platform-neutral.)
# shellcheck source=./common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"
target_init "${1:-}"

WEB_SRC="$REPO_ROOT/apps/web"
OUT="$RES_DIR/web"

log "npm ci"
(cd "$WEB_SRC" && npm ci)

log "next build (NEXT_PUBLIC_AUTH_ENABLED=0)"
(
  cd "$WEB_SRC" || exit 1
  unset NEXT_PUBLIC_API_BASE
  NEXT_PUBLIC_AUTH_ENABLED=0 npm run build
)

SA="$WEB_SRC/.next/standalone"
[ -d "$SA" ] || die "no .next/standalone — is output:'standalone' set in next.config.ts?"

rm -rf "$OUT"
mkdir -p "$OUT"

if [ -f "$SA/server.js" ]; then
  # Flat layout (what the Docker build produces): server.js at the root.
  cp -R "$SA/." "$OUT/"
  mkdir -p "$OUT/.next"
  cp -R "$WEB_SRC/.next/static" "$OUT/.next/static"
  cp -R "$WEB_SRC/public" "$OUT/public"
else
  # Workspace-nested layout: Next inferred a tracing root above apps/web (parent
  # lockfiles on a dev box do this), so server.js sits at <rel>/server.js with
  # the shared node_modules at the tree root. Keep the whole tree, put static
  # and public where the nested server.js expects them, and shim a root
  # server.js so the supervisor's contract (cwd resources/web, `node server.js`)
  # holds either way.
  NESTED="$(cd "$SA" && find . -maxdepth 4 -name server.js -not -path '*/node_modules/*' | head -1)"
  [ -n "$NESTED" ] || die "no server.js anywhere under .next/standalone"
  REL="$(dirname "$NESTED")"
  log "nested standalone layout detected ($REL)"
  cp -R "$SA/." "$OUT/"
  mkdir -p "$OUT/$REL/.next"
  cp -R "$WEB_SRC/.next/static" "$OUT/$REL/.next/static"
  cp -R "$WEB_SRC/public" "$OUT/$REL/public"
  printf "// auto-generated by stage-web.sh — nested standalone shim\nrequire('./%s/server.js');\n" "$REL" > "$OUT/server.js"
fi

[ -f "$OUT/server.js" ] || die "staging failed: $OUT/server.js missing"
log "web staged: $OUT ($(du -sh "$OUT" | awk '{print $1}'))"
