"""curriculum: block fields + assignment/progress/lessonlog

Revision ID: 31ed03f2df02
Revises: 4b44fbf6e38f
Create Date: 2026-07-08 01:40:01.526305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ed03f2df02'
down_revision: Union[str, Sequence[str], None] = '4b44fbf6e38f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('curriculum_block_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_block_id'], ['block.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_curriculum_block_id'), 'assignment', ['curriculum_block_id'], unique=False)
    op.create_index(op.f('ix_assignment_student_id'), 'assignment', ['student_id'], unique=False)
    op.create_table('lesson_log',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('session_block_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('taught', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('homework', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_block_id'], ['block.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_log_session_block_id'), 'lesson_log', ['session_block_id'], unique=False)
    op.create_index(op.f('ix_lesson_log_student_id'), 'lesson_log', ['student_id'], unique=False)
    op.create_table('progress',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['block.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_block_id'), 'progress', ['block_id'], unique=False)
    op.create_index(op.f('ix_progress_student_id'), 'progress', ['student_id'], unique=False)
    op.add_column('block', sa.Column('target_profile', sa.JSON(), nullable=True))
    op.add_column('block', sa.Column('student_id', sa.UUID(), nullable=True))
    # NOTE: hand-added `server_default='content'` — autogenerate emitted this as
    # `nullable=False` with no default, which fails against the app DB's *existing*
    # block rows (48 at the time of writing this migration): Postgres backfills
    # a NOT NULL ADD COLUMN with the server_default when one is given, otherwise
    # it errors with "column ... contains null values". The model's own
    # `default="content"` is Python/ORM-side only (matches the codebase's existing
    # convention for kind/language/is_template/order, all set at table-creation
    # time when there were no pre-existing rows to backfill) and Alembic autogenerate
    # doesn't pick that up as a server_default. Verified this fails without the fix
    # via a rolled-back `ALTER TABLE block ADD COLUMN plane VARCHAR(10) NOT NULL`
    # against `guitar` directly before adding this.
    op.add_column('block', sa.Column('plane', sa.String(length=10), nullable=False, server_default='content'))
    op.create_index(op.f('ix_block_student_id'), 'block', ['student_id'], unique=False)
    op.create_foreign_key('fk_block_student_id', 'block', 'student', ['student_id'], ['id'], ondelete='CASCADE')
    # NOTE: hand-removed an autogenerated `op.drop_index('ix_chunk_embedding_hnsw', ...)`
    # here. That index was created with raw SQL in 4b44fbf6e38f (an expression
    # index casting to halfvec — see that migration's comment for why), so it
    # isn't represented in the ORM metadata; autogenerate diffs metadata
    # against the live DB and, not finding a matching declared index, treats
    # it as "removed" and proposes dropping it. This migration has nothing to
    # do with that index — keeping the drop would have silently destroyed the
    # chunk embedding similarity index the first time this migration ran.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # (matching hand-removal of the paired autogenerated drop_index in upgrade();
    # ix_chunk_embedding_hnsw is untouched by this migration either direction)
    op.drop_constraint('fk_block_student_id', 'block', type_='foreignkey')
    op.drop_index(op.f('ix_block_student_id'), table_name='block')
    op.drop_column('block', 'plane')
    op.drop_column('block', 'student_id')
    op.drop_column('block', 'target_profile')
    op.drop_index(op.f('ix_progress_student_id'), table_name='progress')
    op.drop_index(op.f('ix_progress_block_id'), table_name='progress')
    op.drop_table('progress')
    op.drop_index(op.f('ix_lesson_log_student_id'), table_name='lesson_log')
    op.drop_index(op.f('ix_lesson_log_session_block_id'), table_name='lesson_log')
    op.drop_table('lesson_log')
    op.drop_index(op.f('ix_assignment_student_id'), table_name='assignment')
    op.drop_index(op.f('ix_assignment_curriculum_block_id'), table_name='assignment')
    op.drop_table('assignment')
    # ### end Alembic commands ###
