"""note: note table

Revision ID: 40e6053e4e5f
Revises: 75cdddc574b0
Create Date: 2026-07-10 06:20:26.184488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e6053e4e5f'
down_revision: Union[str, Sequence[str], None] = '75cdddc574b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('promoted_to_knowledge', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_student_id'), 'note', ['student_id'], unique=False)
    # NOTE: hand-removed an autogenerated `op.drop_index('ix_chunk_embedding_hnsw', ...)`
    # here — same recurring false positive documented in 31ed03f2df02/b2335b2917ed:
    # that index was created with raw SQL in 4b44fbf6e38f (an expression index
    # casting to halfvec, since pgvector's HNSW cap on plain `vector` is 2000 dims
    # but chunk.embedding is 2560), so it isn't represented in the ORM metadata;
    # autogenerate diffs metadata against the live DB and, not finding a matching
    # declared index, proposes dropping it every time ANY migration is generated.
    # This migration only adds the `note` table and has nothing to do with that
    # index — keeping the drop would have silently destroyed the chunk embedding
    # similarity index the first time this ran.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # (matching hand-removal of the paired autogenerated create_index in upgrade();
    # ix_chunk_embedding_hnsw is untouched by this migration either direction)
    op.drop_index(op.f('ix_note_student_id'), table_name='note')
    op.drop_table('note')
    # ### end Alembic commands ###
