"""message citations

Revision ID: 48b651d5a4a0
Revises: b99be604d5f6
Create Date: 2026-07-13 02:28:40.055261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b651d5a4a0'
down_revision: Union[str, Sequence[str], None] = 'b99be604d5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: hand-removed an autogenerated `op.drop_index('ix_chunk_embedding_hnsw',
    # ...)` here — same recurring false positive documented in
    # 31ed03f2df02/b2335b2917ed/941529f538af/8fa57b72fb21/75cdddc574b0/
    # b99be604d5f6: that index was created with raw SQL in 4b44fbf6e38f (an
    # expression index casting to halfvec, since pgvector's HNSW cap on plain
    # `vector` is 2000 dims but chunk.embedding is 2560), so it isn't
    # represented in the ORM metadata; autogenerate diffs metadata against the
    # live DB and, not finding a matching declared index, proposes dropping it.
    # This migration only adds `message.citations` (Plan 11 Task 1, C2) and has
    # nothing to do with that index — keeping the drop would have silently
    # destroyed the chunk embedding similarity index the first time this ran.
    op.add_column('message', sa.Column('citations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # (matching hand-removal of the paired autogenerated create_index in
    # upgrade(); ix_chunk_embedding_hnsw is untouched by this migration either
    # direction)
    op.drop_column('message', 'citations')
    # ### end Alembic commands ###
