"""brain: source domain/error/char_count + chunk hnsw index

Revision ID: 4b44fbf6e38f
Revises: 15963c204a07
Create Date: 2026-07-07 02:33:50.265517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b44fbf6e38f'
down_revision: Union[str, Sequence[str], None] = '15963c204a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_source', sa.Column('domain', sa.String(length=30), nullable=True))
    op.add_column('knowledge_source', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('knowledge_source', sa.Column('char_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    # NOTE: deviates from the Task 1 brief's literal
    #   op.create_index(..., postgresql_ops={"embedding": "vector_cosine_ops"})
    # which fails at runtime:
    #   psycopg.errors.ProgramLimitExceeded: column cannot have more than 2000
    #   dimensions for hnsw index
    # pgvector caps HNSW (and IVFFlat) on the `vector` type at 2000 dimensions,
    # regardless of opclass; chunk.embedding is vector(2560). pgvector's
    # documented workaround is an expression index cast to halfvec, which raises
    # the HNSW cap to 4000 dims (halfvec = float16 storage, used only for the
    # index — the underlying column stays full-precision vector(2560)). Verified
    # directly in psql before writing this migration. See report for detail.
    op.execute(
        "CREATE INDEX ix_chunk_embedding_hnsw ON chunk "
        "USING hnsw ((embedding::halfvec(2560)) halfvec_cosine_ops) "
        "WITH (m = 16, ef_construction = 64)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_chunk_embedding_hnsw", table_name="chunk")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_source', 'char_count')
    op.drop_column('knowledge_source', 'error')
    op.drop_column('knowledge_source', 'domain')
    # ### end Alembic commands ###
