"""chat: HITL chat_session/message/approval_request tables

Revision ID: 8fa57b72fb21
Revises: 941529f538af
Create Date: 2026-07-10 02:42:10.046554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa57b72fb21'
down_revision: Union[str, Sequence[str], None] = '941529f538af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_session',
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_request',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=50), nullable=False),
    sa.Column('tool_args', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('edited_args', sa.JSON(), nullable=True),
    sa.Column('result_ref', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_request_session_id'), 'approval_request', ['session_id'], unique=False)
    op.create_table('message',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_session_id'), 'message', ['session_id'], unique=False)
    # NOTE: hand-removed an autogenerated `op.drop_index('ix_chunk_embedding_hnsw', ...)`
    # here — same false positive documented in 31ed03f2df02/b2335b2917ed/941529f538af:
    # that index was created with raw SQL in 4b44fbf6e38f (an expression index
    # casting to halfvec, since pgvector's HNSW cap on plain `vector` is 2000
    # dims but chunk.embedding is 2560), so it isn't represented in the ORM
    # metadata; autogenerate diffs metadata against the live DB and, not
    # finding a matching declared index, proposes dropping it. This migration
    # only adds the 3 new chat tables and has nothing to do with that index —
    # keeping the drop would have silently destroyed the chunk embedding
    # similarity index the first time this ran.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # (matching hand-removal of the paired autogenerated create_index in upgrade();
    # ix_chunk_embedding_hnsw is untouched by this migration either direction)
    op.drop_index(op.f('ix_message_session_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_approval_request_session_id'), table_name='approval_request')
    op.drop_table('approval_request')
    op.drop_table('chat_session')
    # ### end Alembic commands ###
