"""generation_job table

Revision ID: 941529f538af
Revises: b2335b2917ed
Create Date: 2026-07-09 22:59:09.106041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '941529f538af'
down_revision: Union[str, Sequence[str], None] = 'b2335b2917ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_job',
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('result_root_id', sa.UUID(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_kind', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: hand-removed an autogenerated `op.drop_index('ix_chunk_embedding_hnsw', ...)`
    # here — same false positive documented in 31ed03f2df02 and b2335b2917ed:
    # that index was created with raw SQL in 4b44fbf6e38f (an expression index
    # casting to halfvec, since pgvector's HNSW cap on plain `vector` is 2000
    # dims but chunk.embedding is 2560), so it isn't represented in the ORM
    # metadata; autogenerate diffs metadata against the live DB and, not
    # finding a matching declared index, proposes dropping it. This migration
    # only adds the `generation_job` table and has nothing to do with that
    # index — keeping the drop would have silently destroyed the chunk
    # embedding similarity index the first time this ran.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # (matching hand-removal of the paired autogenerated create_index in upgrade();
    # ix_chunk_embedding_hnsw is untouched by this migration either direction)
    op.drop_table('generation_job')
    # ### end Alembic commands ###
