"""curriculum interview table

Revision ID: ae7aefc844e9
Revises: 48b651d5a4a0
Create Date: 2026-07-13 09:56:21.103725

Adds `curriculum_interview` only — the persisted state for Plan 12 Task 3's
guided curriculum interview (`app.models.interview.CurriculumInterview`; see
that model's own docstring for why this is a purpose-built table rather than
reusing `GenerationJob.params`). No `ForeignKey` on this table at all (every
constraint that DOES exist is named explicitly below, satisfying this task's
own "name every constraint" requirement — there just isn't an unnamed FK to
find here, deliberately: see the model docstring's point 3).

NOTE: hand-removed an autogenerated `op.create_unique_constraint(
'uq_page_source_page_no', 'page', ...)` (and its paired `drop_constraint` in
downgrade()) here — PRE-EXISTING drift between `guitar_test`'s live schema
and the migration history, NOT something this task touches: migration
b99be604d5f6 already adds that exact constraint, several revisions before
this one on this same chain, yet `guitar_test` doesn't have it applied.
Autogenerate diffs metadata against the live DB, so it re-proposed a
constraint this migration has nothing to do with — same class of false
positive as the well-documented `ix_chunk_embedding_hnsw` drops on
15963c204a07/31ed03f2df02/8fa57b72fb21/941529f538af/f73763fd9f1e/
b99be604d5f6 (an expression-index vs. plain-metadata mismatch there; a
schema-history-vs-live-DB mismatch here) — left for whoever owns that drift
to investigate, rather than silently folded into an unrelated migration.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae7aefc844e9'
down_revision: Union[str, Sequence[str], None] = '48b651d5a4a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'curriculum_interview',
        sa.Column('step', sa.String(length=20), nullable=False),
        sa.Column('title', sa.String(length=400), nullable=False),
        sa.Column('domain', sa.String(length=30), nullable=True),
        sa.Column('answers', sa.JSON(), nullable=False),
        sa.Column('preview', sa.JSON(), nullable=True),
        sa.Column('job_id', sa.UUID(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('curriculum_interview_pkey')),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('curriculum_interview')
