"""blueprint_default — the tutor's edited SETTINGS-default lesson blueprint

Revision ID: b1c2d3e4f5a6
Revises: c4d9e1f7a230
Create Date: 2026-07-18

ADDITIVE — one new table, nothing existing touched, read, or locked. `alembic
upgrade head` runs in the api container's CMD at boot; this migration only
`CREATE TABLE`s, so it is safe to run against a live database mid-flight.

THE TABLE STARTS EMPTY AND STAYS EMPTY UNTIL THE TUTOR EDITS THE DEFAULT. There is
deliberately no data migration seeding the current blueprint into it — the default
lives in code (`app.curriculum.blueprint.default_blueprint()`, in git, pinned by the
schema-golden and byte-identical-regression tests). An empty table means "new courses
get the code default", which is the state every install is in and the state Reset
(`DELETE /blueprint/default`) returns to. See `models/blueprint_default.py`.

ONE ROW, enforced by a CHECK (`id = 1`) so the singleton is a database guarantee,
not a router convention — same shape as `app_setting` (`ae7aefc844e9`).

Hand-written, not autogenerated, for the reason `b7e2c9a04f31`, `ae7aefc844e9` and
`c1a7d5f0e3b4` all document: `--autogenerate` against `guitar_test` re-proposes
pre-existing drift that has nothing to do with this table. `created_at`/`updated_at`
mirror `TimestampMixin` (`models/base.py`) exactly, as `b7e2c9a04f31` did.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "b1c2d3e4f5a6"
down_revision: Union[str, Sequence[str], None] = "c4d9e1f7a230"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "blueprint_default",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("blueprint", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_blueprint_default"),
        sa.CheckConstraint("id = 1", name="blueprint_default_singleton"),
    )


def downgrade() -> None:
    op.drop_table("blueprint_default")
