"""artifact: artifact table

Revision ID: b2335b2917ed
Revises: 31ed03f2df02
Create Date: 2026-07-08 04:37:28.456832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2335b2917ed'
down_revision: Union[str, Sequence[str], None] = '31ed03f2df02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact',
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['block.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifact_block_id'), 'artifact', ['block_id'], unique=False)
    # NOTE: hand-removed an autogenerated `op.drop_index('ix_chunk_embedding_hnsw', ...)`
    # here — same false positive documented in 31ed03f2df02: that index was created
    # with raw SQL in 4b44fbf6e38f (an expression index casting to halfvec, since
    # pgvector's HNSW cap on plain `vector` is 2000 dims but chunk.embedding is
    # 2560), so it isn't represented in the ORM metadata; autogenerate diffs
    # metadata against the live DB and, not finding a matching declared index,
    # proposes dropping it. This migration only adds the `artifact` table and has
    # nothing to do with that index — keeping the drop would have silently
    # destroyed the chunk embedding similarity index the first time this ran.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # (matching hand-removal of the paired autogenerated create_index in upgrade();
    # ix_chunk_embedding_hnsw is untouched by this migration either direction)
    op.drop_index(op.f('ix_artifact_block_id'), table_name='artifact')
    op.drop_table('artifact')
    # ### end Alembic commands ###
