"""prompt_override + prompt_override_history

Revision ID: b7e2c9a04f31
Revises: a1b2c3d4e5f6
Create Date: 2026-07-17

ADDITIVE — two new tables, nothing touched. `alembic upgrade head` runs in the
api container's CMD at boot, and the tutor's library (140 pages, 5 books) is
being re-OCR'd as this ships: no existing table is read, altered or locked here.

BOTH TABLES START EMPTY, AND STAY EMPTY UNTIL HE EDITS SOMETHING. There is
deliberately no data migration seeding the current prompt text into
`prompt_override`. The defaults live in CODE (`students/context.py::STUDENT_PITCH`
and friends) — an empty table means "the app says exactly what its source says",
which is the state every install is in and the state Reset returns to. Seeding
them would make a migration the place prompts change and quietly demote the code
to a suggestion. See `models/prompt.py`.

`slice_id` is the PK of `prompt_override` (one slice, one override — enforced by
the database, not by the router remembering) and a plain indexed column on
`prompt_override_history` (many snapshots per slice). No FK between them on
purpose: the snapshot taken when an override is DELETED is the most valuable row
in the table, and an FK would either forbid that delete or cascade the text away.

Hand-written, not autogenerated, for the reason `ae7aefc844e9` and `c1a7d5f0e3b4`
both document: `--autogenerate` against `guitar_test` re-proposes pre-existing
drift (`uq_page_source_page_no`, the dead `ix_chunk_embedding_hnsw`) that has
nothing to do with these tables.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "b7e2c9a04f31"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "prompt_override",
        sa.Column("slice_id", sa.String(length=80), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("slice_id", name="pk_prompt_override"),
    )
    op.create_table(
        "prompt_override_history",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("slice_id", sa.String(length=80), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "replaced_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_prompt_override_history"),
    )
    op.create_index(
        "ix_prompt_override_history_slice_id",
        "prompt_override_history",
        ["slice_id"],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_prompt_override_history_slice_id", table_name="prompt_override_history"
    )
    op.drop_table("prompt_override_history")
    op.drop_table("prompt_override")
