"""page source_page_no unique constraint

Revision ID: b99be604d5f6
Revises: f73763fd9f1e
Create Date: 2026-07-12 08:59:39.119802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b99be604d5f6'
down_revision: Union[str, Sequence[str], None] = 'f73763fd9f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: hand-removed an autogenerated `op.drop_index('ix_chunk_embedding_hnsw', ...)`
    # here — same false positive documented in 31ed03f2df02/8fa57b72fb21/941529f538af/
    # f73763fd9f1e: that index was created with raw SQL in 4b44fbf6e38f (an
    # expression index casting to halfvec, since pgvector's HNSW cap on plain
    # `vector` is 2000 dims but chunk.embedding is 2560), so it isn't represented
    # in the ORM metadata; autogenerate diffs metadata against the live DB and,
    # not finding a matching declared index, proposes dropping it. This
    # migration only adds the (source_id, page_no) unique constraint on `page`
    # and has nothing to do with that index — keeping the drop would have
    # silently destroyed the chunk embedding similarity index the first time
    # this ran.
    op.create_unique_constraint('uq_page_source_page_no', 'page', ['source_id', 'page_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_page_source_page_no', 'page', type_='unique')
    # (matching hand-removal of the paired autogenerated create_index in
    # upgrade(); ix_chunk_embedding_hnsw is untouched by this migration either
    # direction)
    # ### end Alembic commands ###
