"""app_setting singleton (the tutor's Anthropic key + model)

Revision ID: c1a7d5f0e3b4
Revises: ae7aefc844e9
Create Date: 2026-07-14 10:00:00.000000

Adds `app_setting` only — Plan 13 Task 3.4. One row, pinned to a fixed UUID by
`app.models.setting.SINGLETON_ID` (see that model's docstring: "first row" would
let two concurrent creators fork the table and hand `GET /settings` and
`get_provider()` different keys).

`anthropic_key_ct` is `Text`, not `String(n)`: it holds a Fernet ciphertext, whose
length is a function of the plaintext and the token envelope, not something worth
guessing a bound for. NULL means "no key yet" — the state every fresh install is
in, and a supported one (`LLMNotConfigured` -> 409, not a 500).

No `ForeignKey` here, so there is no unnamed constraint to leave behind; the two
constraints that do exist (the PK and nothing else) are named explicitly below.

Hand-written, not autogenerated, for the same reason ae7aefc844e9 documents:
`--autogenerate` against `guitar_test` re-proposes pre-existing drift
(`uq_page_source_page_no`, the dead `ix_chunk_embedding_hnsw`) that has nothing
to do with this table.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c1a7d5f0e3b4"
down_revision: Union[str, None] = "ae7aefc844e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "app_setting",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("anthropic_key_ct", sa.Text(), nullable=True),
        sa.Column("model", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_app_setting"),
    )


def downgrade() -> None:
    op.drop_table("app_setting")
