"""concept + concept_claim + concept_alias + book_compile — the concept canon (Part B, C1)

Revision ID: c4d9e1f7a230
Revises: b7e2c9a04f31
Create Date: 2026-07-17

ADDITIVE — four new tables, nothing existing touched, read, altered or locked.
That is not a stylistic claim, it is the deployment constraint: the tutor's
library is being re-OCR'd RIGHT NOW (Hunter 184pp, then Gallagher 388pp, ~10-20h
on his own subscription), the api container's boot CMD is
`alembic upgrade head && exec uvicorn` under `restart: unless-stopped`, and a DB
ahead of the image crash-loops that container and kills the run. So this file is
written to be inert against every row that exists today, and it is verified on a
SCRATCH database rather than applied to the live one — it lands at the next api
build, which is the same moment the code that reads it lands. A prior agent
applied a canon migration to the live DB and had to roll it back; that is the
mistake this paragraph exists to prevent from happening twice.

ALL FOUR TABLES START EMPTY. There is no data migration and there could not be
one: the canon is produced by reading books with a model, which costs real money,
and `canon/compile.compile_book` is deliberately never automatic. An `upgrade`
that populated anything here would be an app update silently spending the tutor's
subscription — the top severity class in this plan.

`ON DELETE CASCADE` ON EVERY FOREIGN KEY, and it is load-bearing rather than
tidy. Deleting a book must take its claims with it: a `concept_claim` row is a
POINTER into a specific book at a specific page (`source_id` + `pages`), and the
canon's whole promise is that the tutor can click one and land on the page it
names. A claim that outlives its book is a chip that opens nothing.

`pages` IS A REAL `integer[]`, NOT JSON, and the difference is invisible until it
isn't. Both round-trip `[47, 48]` through SQLAlchemy identically; no Python
assertion distinguishes them. Then Pass 5 hydrates a lesson with
`WHERE 47 = ANY(pages)` — which a JSON column answers with a syntax error, at the
far end of the project from this decision.

Hand-written, not autogenerated, for the reason `b7e2c9a04f31`, `ae7aefc844e9`
and `c1a7d5f0e3b4` all document: `--autogenerate` against `guitar_test`
re-proposes pre-existing drift (`uq_page_source_page_no`, the dead
`ix_chunk_embedding_hnsw`) that has nothing to do with these tables. It would
also have had to point at a live database mid-OCR to see the current state.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "c4d9e1f7a230"
down_revision: Union[str, Sequence[str], None] = "b7e2c9a04f31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "concept",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        # varchar(120), UNIQUE: the second book to name a concept exactly what the
        # first one did reuses the row — a free reconciliation, before C3 runs at
        # all. The constraint is also what makes `_get_or_create` an upsert rather
        # than a race between two books compiling concurrently.
        sa.Column("key", sa.String(length=120), nullable=False),
        # Text, not varchar(N): these are the MODEL'S OWN WORDS naming the concept
        # (no pre-fixed vocabulary — see `models/canon.py`), and a length cap here
        # would truncate a long name into a different, colliding concept.
        sa.Column("label_en", sa.Text(), nullable=False),
        sa.Column("label_el", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ONE unique index, not a UniqueConstraint plus a plain index. `Concept.key` is
    # `mapped_column(..., unique=True, index=True)`, which SQLAlchemy renders as
    # exactly this single unique index — and `alembic check` fails the pair, which
    # is how the first draft of this file was caught proposing both.
    op.create_index(op.f("ix_concept_key"), "concept", ["key"], unique=True)

    op.create_table(
        "concept_claim",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("concept_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("source_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("pages", sa.ARRAY(sa.Integer()), nullable=False),
        # Free-form, 40 chars: the author's POSITION in the model's own words. An
        # enum here would flatten two authors' disagreement into one bucket, and
        # the disagreement is the product.
        sa.Column("stance", sa.String(length=40), nullable=True),
        sa.Column("depth", sa.String(length=20), nullable=True),
        # The [FIGURE] contract, persisted: "author" = quotable as the book's own
        # words, "figure" = our description of a picture, citable but NEVER
        # quotable. NOT NULL with no default — a claim whose provenance nobody
        # decided is exactly the one that gets quoted wrongly.
        sa.Column("grounding", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["concept_id"], ["concept.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["knowledge_source.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_concept_claim_concept_id"), "concept_claim",
                    ["concept_id"], unique=False)
    op.create_index(op.f("ix_concept_claim_source_id"), "concept_claim",
                    ["source_id"], unique=False)

    op.create_table(
        "concept_alias",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("concept_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("source_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("alias", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["concept_id"], ["concept.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["knowledge_source.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        # One book calls one concept one thing — so a re-compile of the same book
        # cannot stack duplicate aliases. Idempotence at the database, not by
        # hoping the writer remembered.
        sa.UniqueConstraint("concept_id", "source_id",
                            name="uq_concept_alias_concept_source"),
    )
    op.create_index(op.f("ix_concept_alias_concept_id"), "concept_alias",
                    ["concept_id"], unique=False)
    op.create_index(op.f("ix_concept_alias_source_id"), "concept_alias",
                    ["source_id"], unique=False)

    op.create_table(
        "book_compile",
        # `source_id` IS the primary key. One book, one compile state — a table
        # that could hold two rows for one book would immediately raise "which is
        # true?", answered by an ORDER BY somewhere. This is also the row
        # `compile_book` checks to refuse re-spending on a book it already read.
        sa.Column("source_id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        # Which model read the book — so "was this compiled by the good model?" is
        # a question the DATA answers rather than a thing someone remembers.
        sa.Column("model", sa.String(length=40), nullable=True),
        sa.Column("compiled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("concept_count", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["knowledge_source.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("source_id"),
    )


def downgrade() -> None:
    # Reverse creation order: `concept_claim` and `concept_alias` both reference
    # `concept`, so `concept` cannot go first.
    op.drop_table("book_compile")
    op.drop_index(op.f("ix_concept_alias_source_id"), table_name="concept_alias")
    op.drop_index(op.f("ix_concept_alias_concept_id"), table_name="concept_alias")
    op.drop_table("concept_alias")
    op.drop_index(op.f("ix_concept_claim_source_id"), table_name="concept_claim")
    op.drop_index(op.f("ix_concept_claim_concept_id"), table_name="concept_claim")
    op.drop_table("concept_claim")
    op.drop_index(op.f("ix_concept_key"), table_name="concept")
    op.drop_table("concept")
