"""planning chat columns (Part 5): chat_session.interview_id + curriculum_interview.planning_brief

Hand-written additive ADD COLUMN NULL (safe mid-flight; runs in the api
container CMD at boot), not autogenerated — see e5f6a7b8c9d0 for why.

Revision ID: c7d8e9f0a1b2
Revises: f1a2b3c4d5e6
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "c7d8e9f0a1b2"
down_revision: Union[str, Sequence[str], None] = "f1a2b3c4d5e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("chat_session", sa.Column("interview_id", sa.Uuid(as_uuid=True), nullable=True))
    op.add_column("curriculum_interview", sa.Column("planning_brief", sa.Text(), nullable=True))


def downgrade() -> None:
    op.drop_column("curriculum_interview", "planning_brief")
    op.drop_column("chat_session", "interview_id")
