"""chat_session.root_id — bind one conversation to one curriculum (Unit D)

ADDITIVE — one nullable column, nothing existing touched, read, or locked.
`alembic upgrade head` runs in the api container's CMD at boot; this migration
only `ADD COLUMN ... NULL`, so it is safe to run against a live database mid-flight
(no table rewrite, no default backfill scan).

A COLUMN, NOT A TABLE, and NOT A ForeignKey — the same decoupling `chat_session.
student_id` already documents (`models/chat.py`): a chat transcript is a
standalone record that must stay readable even if the curriculum it references is
later edited or deleted. An FK CASCADE would wipe a conversation as a side effect
of a board edit; SET NULL would erase the very context a history needs. A stale id
is the accepted tradeoff — the router's transient context injection simply skips a
root that no longer resolves to a course.

Hand-written, not autogenerated, for the reason `b1c2d3e4f5a6`/`b7e2c9a04f31`
already document: `--autogenerate` against `guitar_test` re-proposes pre-existing
drift unrelated to this column.

Revision ID: e5f6a7b8c9d0
Revises: b1c2d3e4f5a6
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "e5f6a7b8c9d0"
down_revision: Union[str, Sequence[str], None] = "b1c2d3e4f5a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "chat_session",
        sa.Column("root_id", sa.Uuid(as_uuid=True), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("chat_session", "root_id")
