"""concept_claim.anchor — the verbatim quote quote-based citations resolve from (Unit B)

Revision ID: f1a2b3c4d5e6
Revises: e5f6a7b8c9d0
Create Date: 2026-07-19

ADDITIVE — one nullable column on an existing table, nothing else touched, read,
altered or locked. Same deployment constraint as `c4d9e1f7a230`: the api boot CMD
is `alembic upgrade head && exec uvicorn` under `restart: unless-stopped`, so a DB
ahead of the image crash-loops the container. This column is inert against every
row that exists today (they get NULL), and it carries no data migration: the
anchor is produced only by (re)compiling a book with the Unit B prompt, which
costs model time, and an `upgrade` that populated it would be an app update
silently spending the tutor's subscription — the top severity class in this plan.

`down_revision` is `e5f6a7b8c9d0` (Unit D's `chat_session.root_id`), which is the
head printed by `alembic heads` at build time — NOT the pre-Unit-C `c4d9e1f7a230`.

Hand-written, not autogenerated, for the reason `e5f6a7b8c9d0`/`b1c2d3e4f5a6`
already document: `--autogenerate` against `guitar_test` re-proposes pre-existing
drift unrelated to this column.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "f1a2b3c4d5e6"
down_revision: Union[str, Sequence[str], None] = "e5f6a7b8c9d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("concept_claim", sa.Column("anchor", sa.Text(), nullable=True))


def downgrade() -> None:
    op.drop_column("concept_claim", "anchor")
