"""library pages collections

Revision ID: f73763fd9f1e
Revises: 40e6053e4e5f
Create Date: 2026-07-12 08:27:43.409657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f73763fd9f1e'
down_revision: Union[str, Sequence[str], None] = '40e6053e4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('page',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ocr_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_source_id'), 'page', ['source_id'], unique=False)
    op.add_column('chunk', sa.Column('page_id', sa.UUID(), nullable=True))
    # NOTE: hand-removed an autogenerated `op.drop_index('ix_chunk_embedding_hnsw', ...)`
    # here — same false positive documented in 31ed03f2df02/8fa57b72fb21/941529f538af:
    # that index was created with raw SQL in 4b44fbf6e38f (an expression index
    # casting to halfvec, since pgvector's HNSW cap on plain `vector` is 2000
    # dims but chunk.embedding is 2560), so it isn't represented in the ORM
    # metadata; autogenerate diffs metadata against the live DB and, not
    # finding a matching declared index, proposes dropping it. This migration
    # only adds Page/Collection and the page_id/collection_id/url columns and
    # has nothing to do with that index — keeping the drop would have
    # silently destroyed the chunk embedding similarity index the first time
    # this ran.
    op.create_index(op.f('ix_chunk_page_id'), 'chunk', ['page_id'], unique=False)
    op.create_foreign_key('fk_chunk_page_id', 'chunk', 'page', ['page_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chunk', 'page')
    op.add_column('knowledge_source', sa.Column('url', sa.String(length=2000), nullable=True))
    op.add_column('knowledge_source', sa.Column('collection_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_knowledge_source_collection_id'), 'knowledge_source', ['collection_id'], unique=False)
    op.create_foreign_key('fk_knowledge_source_collection_id', 'knowledge_source', 'collection', ['collection_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_knowledge_source_collection_id', 'knowledge_source', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_source_collection_id'), table_name='knowledge_source')
    op.drop_column('knowledge_source', 'collection_id')
    op.drop_column('knowledge_source', 'url')
    op.add_column('chunk', sa.Column('page', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_chunk_page_id', 'chunk', type_='foreignkey')
    op.drop_index(op.f('ix_chunk_page_id'), table_name='chunk')
    # (matching hand-removal of the paired autogenerated drop_index in upgrade();
    # ix_chunk_embedding_hnsw is untouched by this migration either direction)
    op.drop_column('chunk', 'page_id')
    op.drop_index(op.f('ix_page_source_id'), table_name='page')
    op.drop_table('page')
    op.drop_table('collection')
    # ### end Alembic commands ###
