"""The guided curriculum-authoring interview, v2.

Chris: "maybe llm can act as an assistant there bro, guiding him, and asking him
questions or corrections throughout the process. thats actually would be dope."

THE STATE MACHINE LIVES HERE, IN CODE, NEVER IN THE MODEL'S HEAD. Plan 10's live
run needed the model three attempts to track a single session id, and Plan 11's
notes call it "unreliable at id-plumbing". A free-form chat asked to remember
which step it is on, what was already answered, and which sources were chosen
would break exactly the same way. Every step, transition and validation rule below
is a plain Python `if`. The model is reached in exactly ONE place — the outline
call — and it never sees `step` or `answers`.

SEVEN STEPS:

  who      -> THE STUDENT IS FULLY OPTIONAL. Chris, verbatim: "this has to be
              optional dude.. the student part here has to be TOTALLY optional".
              So "no student, all levels" is a first-class answer with its own
              option, not a field left blank — and when there IS no student there
              is an explicit LEVEL selector, because "who is this for" and "how
              advanced are they" are two questions and only one of them needs a
              person.
  duration -> weeks x sessions/week x minutes, and it ECHOES THE DERIVED SHAPE
              back at him: "20 sessions -> 5 modules x 4 lessons -> ~2,200 words
              each". He is agreeing to a SIZE before we spend his money on it.
              This is where "20 weeks, 4 modules" stops being possible.
  scope    -> a free-text COURSE BRIEF, plus the gap policy.

              **`domain` IS DEAD.** Chris asked: "is domain playing any role? is
              it used somewhere or only for tagging?" It was ONE line in one
              prompt ("Domain: {domain}") plus a retrieval filter that, after
              5d77bd0, could no longer exclude anything. It never tagged a
              curriculum and never rendered anywhere. A 30-character tag was
              standing in for the thing he actually wanted to say, which is what
              this course is FOR — so now he says it, in his own words, and it
              reaches the outline prompt AND every lesson-draft prompt.
  structure -> Plan C's addition. OPTIONAL + SKIPPABLE, pre-filled with the
              settings default (`resolve_default_blueprint`): the 8-section
              lesson skeleton every lesson in this course will draft from. Skip
              -> the settings default is used at confirm (spec invariant #7).
              Sits here (between scope and sources) rather than later, because
              it shapes lesson DRAFTING, not the outline the "outline" step
              edits — it must not disturb that step's existing auto-regenerate
              handoff with "sources".
  sources  -> which of his library sources to draw on. Every source is listed
              with its size, and the step reports what the selection MEASURES:
              "3 sources · 92,400 tokens · fits whole". Above the budget it says
              so, honestly, rather than silently degrading to retrieval.
  outline  -> the outline, generated by a model that has READ THE WHOLE LIBRARY,
              with a per-module tier IT assigned. He EDITS it. This replaces the
              old "preview" step, whose gap flags came from a cosine floor with a
              0.021 separation margin.
  confirm  -> materialize the tree (so the board opens instantly on 20 queued
              lessons) and enqueue the draft fan-out. 202 {job_id, root_id}.

VALIDATION: every step's answer either advances the step or returns an error and
LEAVES THE STEP UNCHANGED. A blank/garbled/invalid answer re-asks the same
question, never crashes, never silently advances.
"""
from __future__ import annotations

import uuid

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.brain.retrieve import MIN_PASSAGE_CHARS
from app.curriculum.blueprint import BlueprintInvalid, validate_blueprint
from app.curriculum.blueprint_store import resolve_default_blueprint
from app.curriculum.corpus import build_curriculum_context, build_library_context
from app.curriculum.outline import (
    GAP_POLICIES,
    POLICY_GENERAL,
    generate_outline,
    materialize_outline,
)
from app.curriculum.shape import plan_shape
from app.i18n import DEFAULT_LOCALE, normalize_locale
from app.llm.factory import get_provider
from app.models.interview import CurriculumInterview
from app.models.knowledge import KnowledgeSource
from app.models.student import Student
from app.prompts.overrides import resolve
from app.students.context import build_student_brief

STEP_ORDER = ["who", "duration", "scope", "structure", "sources", "outline", "confirm"]

# The levels offered when no student is chosen. "all_levels" is the DEFAULT and it
# is not a cop-out: a tutor building a course for his whole roster is the common
# case, and forcing him to pick "beginner" would silently pitch every lesson at
# the least advanced student he has.
LEVELS = ("all_levels", "beginner", "intermediate", "advanced")


def start_interview(db: Session, *, title: str) -> CurriculumInterview:
    """Create a fresh interview at "who" and commit it.

    `title` is the one piece of context the interview does not ask about
    step-by-step — the tutor already named the course to get here, exactly as he
    does on the non-interview form.
    """
    interview = CurriculumInterview(step="who", title=title, answers={})
    db.add(interview)
    db.commit()
    db.refresh(interview)
    return interview


# ---------------------------------------------------------------------------
# Reading the current step
# ---------------------------------------------------------------------------

def _shape_of(interview: CurriculumInterview):
    duration = interview.answers.get("duration") or {}
    if not duration.get("weeks"):
        return None
    return plan_shape(
        duration["weeks"],
        duration.get("sessions_per_week", 1),
        duration.get("minutes_per_session", 50),
    )


def describe_step(db: Session, interview: CurriculumInterview) -> dict:
    """The `{question, options, findings}` for the CURRENT step. Never mutates,
    never touches the model — every read path (start, a non-final answer, and a
    refresh via GET) renders through here, so all three agree."""
    step = interview.step

    if step == "who":
        students = db.scalars(select(Student).order_by(Student.name)).all()
        options = [
            {
                "value": "none",
                "label": "No particular student — a course for anyone",
                "kind": "none",
            },
            *[
                {
                    "value": str(s.id),
                    "label": s.name + (f" ({s.level})" if s.level else ""),
                    "kind": "student",
                }
                for s in students
            ],
        ]
        return {
            "question": (
                "Who is this curriculum for? Pick a student, or build it for no "
                "one in particular — that is a perfectly normal answer, and then "
                "you just tell me the level."
            ),
            "options": options,
            "findings": {"levels": list(LEVELS)},
        }

    if step == "duration":
        return {
            "question": (
                "How long does this course run? Give me the number of weeks, how "
                "many sessions per week, and how many minutes a session."
            ),
            "options": None,
            "findings": None,
        }

    if step == "scope":
        return {
            "question": (
                "In your own words: what is this course FOR? What should the "
                "student be able to do at the end of it, and what do you want "
                "covered? And — when your library doesn't cover something, what "
                "should I do?"
            ),
            "options": [
                {
                    "value": "library_only",
                    "label": "Only my library. Show me the gaps instead of filling them.",
                },
                {
                    "value": "general_knowledge",
                    "label": "Fill the gaps from general knowledge, clearly labelled.",
                },
            ],
            "findings": None,
        }

    if step == "structure":
        return {
            "question": (
                "This is the STRUCTURE every lesson in this course will follow — "
                "the sections, how much of the lesson time each one gets, and "
                "who it's for. The standard structure works well for most "
                "courses; skip this if you don't want to change it."
            ),
            "options": None,
            # The pre-fill: his edited settings default if he has one, else the
            # code default (`resolve_default_blueprint`'s own contract) — never
            # `default_blueprint()` directly, which would silently ignore a
            # settings-level customisation the moment he opens the wizard.
            "findings": {"blueprint": resolve_default_blueprint(db)},
        }

    if step == "sources":
        sources = db.scalars(select(KnowledgeSource).order_by(KnowledgeSource.title)).all()
        options = [
            {
                "value": str(s.id),
                "label": s.title,
                "type": s.type,
                "char_count": s.char_count,
                # A suggestion, never a silent exclusion — every source is listed.
                # `MIN_PASSAGE_CHARS` is the same "is this substantive" cutoff the
                # retrieval floor uses, reused here rather than a second arbitrary
                # number.
                "default_selected": (s.char_count or 0) >= MIN_PASSAGE_CHARS,
            }
            for s in sources
        ]
        shape = _shape_of(interview)
        return {
            "question": (
                "Which of your sources should this course be built from? I read "
                "them WHOLE — not a search over them — so what you pick here is "
                "literally what the model reads."
            ),
            "options": options,
            # The NUMBERS, not a sentence. The API does not know the tutor's
            # locale, and `Shape.describe()` is English — rendering it verbatim
            # put an English line on a fully Greek page. The frontend holds both
            # translations; let it format.
            "findings": (
                {
                    "shape": {
                        "lessons_total": shape.lessons_total,
                        "modules": shape.modules,
                        "lessons_per_module": list(shape.lessons_per_module),
                        "target_words_per_lesson": shape.target_words_per_lesson,
                        "teaching_minutes": shape.teaching_minutes,
                        "qa_minutes": shape.qa_minutes,
                    }
                }
                if shape
                else None
            ),
        }

    if step == "outline":
        return {
            "question": (
                "Here is the course. Edit anything — rename, reorder, add, delete, "
                "change a module's tier. Nothing has been drafted yet, so this is "
                "the cheap moment to change your mind."
            ),
            "options": None,
            "findings": interview.outline,
        }

    if step == "confirm":
        return {
            "question": (
                "Ready? I'll write all the lessons in the background — you can "
                "watch them arrive, and read module 1 while module 5 is still "
                "being written."
            ),
            "options": None,
            "findings": interview.outline,
        }

    return {
        "question": "This curriculum is being written.",
        "options": None,
        "findings": interview.outline,
    }


def render_state(db: Session, interview: CurriculumInterview, *, error: str | None = None) -> dict:
    """The full envelope every route returns."""
    info = describe_step(db, interview)
    return {
        "interview_id": interview.id,
        "step": interview.step,
        "error": error,
        "root_id": interview.root_id,
        "job_id": interview.job_id,
        **info,
    }


# ---------------------------------------------------------------------------
# Answering
# ---------------------------------------------------------------------------

def _reask(error: str) -> dict:
    return {"ok": False, "error": error, "done": False}


def _ok(*, done: bool = False) -> dict:
    return {"ok": True, "error": None, "done": done}


def _parse_uuid(value) -> uuid.UUID | None:
    try:
        return uuid.UUID(str(value))
    except (ValueError, AttributeError, TypeError):
        return None


def _answer_who(db: Session, interview: CurriculumInterview, answer) -> dict:
    """The student is OPTIONAL — `{"student_id": null}` and `{"level": "all_levels"}`
    are both complete, valid answers. The only thing this step can reject is a
    student id that does not exist, or a level that is not one of ours."""
    if not isinstance(answer, dict):
        return _reask("Pick a student, or choose 'no particular student' and give me a level.")

    raw = answer.get("student_id")
    level = answer.get("level") or "all_levels"
    if level not in LEVELS:
        return _reask(f"'{level}' isn't a level I know. Pick one of: {', '.join(LEVELS)}.")

    if raw in (None, "", "none"):
        who = {"student_id": None, "name": None, "level": level, "language": DEFAULT_LOCALE}
    else:
        student_id = _parse_uuid(raw)
        student = db.get(Student, student_id) if student_id else None
        if student is None:
            return _reask("I don't recognize that student — pick one from the list.")
        who = {
            "student_id": str(student.id),
            "name": student.name,
            # The student's OWN level wins over the selector when he has one on
            # file — the selector exists for the case where there is no student to
            # ask. `all_levels` from the picker is not an override, it is a default.
            "level": student.level or (level if level != "all_levels" else None),
            # Normalized: `preferred_language` is free text the agent tools can
            # write ("el-GR", "EL"), and un-normalized it lands verbatim on
            # Block.language, where anything not exactly "el"/"en" used to flip
            # the persisted section headings to English.
            "language": normalize_locale(student.preferred_language),
        }

    interview.answers = {**interview.answers, "who": who}
    return _ok()


def _answer_duration(interview: CurriculumInterview, answer) -> dict:
    if not isinstance(answer, dict):
        return _reask("Give me weeks, sessions_per_week and minutes_per_session as numbers.")

    weeks = answer.get("weeks")
    per_week = answer.get("sessions_per_week", 1)
    minutes = answer.get("minutes_per_session")
    # bool is an int subclass in Python — reject it explicitly, or {"weeks": true}
    # sails through as a 1-week course.
    if any(isinstance(v, bool) for v in (weeks, per_week, minutes)):
        return _reask("Give me weeks, sessions_per_week and minutes_per_session as numbers.")
    try:
        weeks_i, per_week_i, minutes_i = int(weeks), int(per_week), int(minutes)
    except (TypeError, ValueError):
        return _reask("Give me weeks, sessions_per_week and minutes_per_session as numbers.")
    if weeks_i <= 0 or per_week_i <= 0 or minutes_i <= 0:
        return _reask("Weeks, sessions per week and minutes must all be greater than 0.")

    interview.answers = {
        **interview.answers,
        "duration": {
            "weeks": weeks_i,
            "sessions_per_week": per_week_i,
            "minutes_per_session": minutes_i,
        },
    }
    return _ok()


def _answer_scope(interview: CurriculumInterview, answer) -> dict:
    if not isinstance(answer, dict):
        return _reask("Tell me what this course is for, in a sentence or two.")

    brief = answer.get("brief")
    if not isinstance(brief, str) or not brief.strip():
        return _reask(
            "Tell me what this course is for — what should the student be able to "
            "do at the end of it? This is what the whole thing gets written from."
        )
    policy = answer.get("gap_policy") or POLICY_GENERAL
    if policy not in GAP_POLICIES:
        return _reask(f"'{policy}' isn't a gap policy I know: {', '.join(GAP_POLICIES)}.")

    interview.brief = brief.strip()
    interview.gap_policy = policy
    interview.answers = {
        **interview.answers, "scope": {"brief": brief.strip(), "gap_policy": policy},
    }
    return _ok()


def _answer_structure(db: Session, interview: CurriculumInterview, answer) -> dict:
    """OPTIONAL + SKIPPABLE (spec invariant #7). `{"skip": true}` advances with
    NOTHING recorded in `interview.answers["structure"]` — `_answer_confirm`
    (Task 3) then falls back to `resolve_default_blueprint(db)`, exactly as if
    this step had never existed. `{"blueprint": {...}}` is validated via
    `validate_blueprint`; on success the NORMALIZED result is stored (never the
    tutor's raw payload, same "store what was actually accepted" rule
    `_answer_scope` follows with `brief.strip()`); on failure this re-asks and
    leaves `interview.step` unchanged, same contract every other step honours."""
    if not isinstance(answer, dict):
        return _reask(
            'Send {"skip": true} to use the standard lesson structure, or '
            '{"blueprint": {...}} to use your own.'
        )

    if answer.get("skip") is True:
        return _ok()

    raw = answer.get("blueprint")
    if not isinstance(raw, dict):
        return _reask(
            'Send {"skip": true} to use the standard lesson structure, or '
            '{"blueprint": {...}} to use your own.'
        )
    try:
        blueprint = validate_blueprint(raw)
    except BlueprintInvalid as e:
        return _reask(f"That structure isn't valid ({e.code}). Fix it, or skip to use the standard one.")

    interview.answers = {**interview.answers, "structure": {"blueprint": blueprint}}
    return _ok()


def _answer_sources(db: Session, interview: CurriculumInterview, answer) -> dict:
    """Validates the selection and MEASURES it. The outline itself is NOT generated
    here — see `_answer_outline`'s docstring for why the expensive call belongs to
    the step that shows its result."""
    if not isinstance(answer, dict) or not isinstance(answer.get("source_ids"), list):
        return _reask(
            "Tell me which source_ids to draw on, as a list ([] is a valid, "
            "deliberate choice to draw on none of them)."
        )

    parsed: list[uuid.UUID] = []
    for raw in answer["source_ids"]:
        sid = _parse_uuid(raw)
        if sid is None:
            return _reask(f"{raw!r} isn't a valid source id.")
        parsed.append(sid)

    if parsed:
        found = set(db.scalars(
            select(KnowledgeSource.id).where(KnowledgeSource.id.in_(parsed))
        ).all())
        missing = [str(p) for p in parsed if p not in found]
        if missing:
            return _reask(f"Unknown source id(s): {', '.join(missing)}.")

    library = build_library_context(db, parsed)
    interview.answers = {
        **interview.answers,
        "sources": {
            "source_ids": [str(p) for p in parsed],
            # The measurement, cached — this is what the tutor is shown, and what
            # makes "does my library fit whole?" a fact rather than a hope.
            "measured": {
                "token_count": library.token_count,
                "fits": library.fits,
                "summary": library.summary(),
                "sources": library.sources,
            },
        },
    }
    return _ok()


def _answer_outline(db: Session, interview: CurriculumInterview, answer) -> dict:
    """`{"regenerate": true}` -> generate (or re-generate) the outline and STAY on
    this step. `{"outline": {...}}` -> accept the tutor's EDITED outline and move
    to confirm.

    THE EDITED OUTLINE IS THE ONE THAT GETS BUILT. Not the model's original. That
    is the entire point of the step — Chris's complaint was that the app gave him
    something to accept or reject, not something to work on. Whatever comes back in
    `answer["outline"]` is what `materialize_outline` persists at confirm.

    The generate call is HERE and not at the end of the sources step, because it is
    the expensive one (90K tokens, ~$0.34, 30-60s) and it belongs to the step that
    shows its result: a tutor who backs out of the sources step and re-picks does
    not pay for an outline he never saw.
    """
    if not isinstance(answer, dict):
        return _reask('Send {"regenerate": true} to draft the outline, or {"outline": {...}} to accept it.')

    # ACCEPTING AN EDIT takes priority, and is decided by the PRESENCE of an
    # "outline" key — never by whether `interview.outline` is set. It used to be
    # gated on `interview.outline is None` meaning "(re)generate", which worked only
    # because generation was SYNCHRONOUS and left `interview.outline` populated
    # before any edit could arrive. Now generation is a background job (see below),
    # so `interview.outline` is None right up until that job writes it — and an edit
    # submitted against a None outline would have been misread as a regenerate
    # request. Whatever comes back here in `answer["outline"]` is what
    # `materialize_outline` persists at confirm; THE EDITED OUTLINE IS THE ONE THAT
    # GETS BUILT, which is the entire point of the step.
    if "outline" in answer:
        edited = answer.get("outline")
        if not isinstance(edited, dict) or not isinstance(edited.get("modules"), list):
            return _reask('Send the outline back as {"outline": {"title": ..., "modules": [...]}}.')
        if not edited["modules"]:
            return _reask("An outline with no modules isn't a course. Add at least one.")
        interview.outline = edited
        return _ok()

    # Otherwise: (RE)GENERATE. The outline call reads the WHOLE library (~340K chars)
    # and runs for up to ~3 minutes — past Cloudflare's ~100s edge timeout under
    # orange-cloud, the exact reason `generate_curriculum_endpoint` and the confirm
    # step already run their model calls OFF the request path. So this no longer
    # GENERATES here; like `_answer_confirm`, it hands the work to the ROUTER, which
    # has the `BackgroundTasks` this function does not: the router enqueues a
    # `GenerationJob(kind="curriculum_outline")` and schedules `run_outline_job`
    # (`app.jobs.runner`), and the tutor polls it. Validate what that job will need
    # NOW, so a missing shape is an immediate re-ask instead of a job that only fails
    # three minutes later.
    if _shape_of(interview) is None:
        return _reask("I don't have the course length yet — go back to the duration step.")
    # Stay on "outline"; the job populates `interview.outline`, then he looks at it.
    return {"ok": True, "error": None, "done": False, "stay": True, "generate_outline": True}


def generate_interview_outline(db: Session, interview: CurriculumInterview) -> dict:
    """Run the interview's expensive full-library outline call and return the outline.

    Called OFF the request path by `app.jobs.runner.run_outline_job` — see
    `routers/curriculum.py::answer_curriculum_interview` for why the outline step is
    async (the call reads the whole library and outlives Cloudflare's ~100s edge
    timeout). Rebuilds exactly the inputs the old synchronous `_answer_outline`
    branch used, from the persisted interview row, so the first run and any refresh
    read the same source of truth. Does NOT commit or assign `interview.outline` —
    the caller owns the transaction (it commits the outline and the job status
    together, so a crash between them can't leave one written without the other)."""
    shape = _shape_of(interview)
    if shape is None:
        # Guarded at enqueue time by `_answer_outline`; defensive only.
        raise ValueError("interview has no course shape yet")
    who = interview.answers.get("who") or {}
    source_ids = [
        uuid.UUID(s) for s in (interview.answers.get("sources") or {}).get("source_ids") or []
    ]
    student_id = _parse_uuid(who.get("student_id")) if who.get("student_id") else None
    library = build_curriculum_context(db, source_ids)
    return generate_outline(
        db,
        title=interview.title,
        brief=interview.brief,
        language=who.get("language") or DEFAULT_LOCALE,
        shape=shape,
        library=library,
        student_brief=build_student_brief(db, student_id),
        gap_policy=interview.gap_policy or POLICY_GENERAL,
    )


def _answer_confirm(db: Session, interview: CurriculumInterview, answer) -> dict:
    """Materialize the tree and hand back. The ROUTER creates the GenerationJob and
    schedules the BackgroundTask — it has the `BackgroundTasks` and this does not,
    exactly as the old confirm step worked."""
    if not isinstance(answer, dict) or answer.get("approved") is not True:
        return _reask('Reply with {"approved": true} to start writing the lessons.')
    if not interview.outline:
        return _reask("There's no outline to build yet.")

    who = interview.answers.get("who") or {}
    shape = _shape_of(interview)
    if shape is None:
        return _reask("I don't have the course length yet — go back to the duration step.")

    source_ids = [
        uuid.UUID(s) for s in (interview.answers.get("sources") or {}).get("source_ids") or []
    ]
    student_id = _parse_uuid(who.get("student_id")) if who.get("student_id") else None
    language = who.get("language") or DEFAULT_LOCALE

    # THE LESSON BLUEPRINT for this course: what the (optional) "structure" step
    # chose, else the settings default. `materialize_outline` freezes it onto
    # `course.meta["blueprint"]`. A skipped/absent structure step leaves no blueprint
    # in `answers`, so the settings default is used (invariant #7).
    structure = interview.answers.get("structure") or {}
    chosen_bp = structure.get("blueprint")
    blueprint = chosen_bp if isinstance(chosen_bp, dict) else resolve_default_blueprint(db)

    root_id = materialize_outline(
        db,
        interview.outline,
        title=interview.title,
        language=language,
        shape=shape,
        library=build_curriculum_context(db, source_ids),
        brief=interview.brief,
        gap_policy=interview.gap_policy or POLICY_GENERAL,
        student_id=student_id,
        source_ids=source_ids,
        profile={
            "student_id": who.get("student_id"),
            "student_name": who.get("name"),
            "level": who.get("level"),
        },
        blueprint=blueprint,
    )
    interview.root_id = root_id
    interview.answers = {**interview.answers, "confirm": {"approved": True}}
    return _ok(done=True)


def answer_interview(db: Session, interview: CurriculumInterview, answer) -> dict:
    """Validate `answer` against the CURRENT step; on success mutate `interview`
    and advance. Returns:

      {"ok": False, "error": "...", "done": False}
        Validation failed. `interview.step` is UNCHANGED — the caller re-asks the
        SAME question. This function NEVER raises on a bad/blank/malformed answer.

      {"ok": True, "done": False}            advanced to the next step
      {"ok": True, "done": False, "stay":True} outline (re)generated; same step
      {"ok": True, "done": True}             confirmed. `interview.root_id` is set;
                                             the ROUTER enqueues the draft job.

    Does not commit — the caller commits once, after inspecting the result.
    """
    step = interview.step
    if step == "who":
        result = _answer_who(db, interview, answer)
    elif step == "duration":
        result = _answer_duration(interview, answer)
    elif step == "scope":
        result = _answer_scope(interview, answer)
    elif step == "structure":
        result = _answer_structure(db, interview, answer)
    elif step == "sources":
        result = _answer_sources(db, interview, answer)
    elif step == "outline":
        result = _answer_outline(db, interview, answer)
    elif step == "confirm":
        result = _answer_confirm(db, interview, answer)
    else:
        return _reask(f"This interview is already at its final step ({step!r}).")

    if result["ok"] and not result.get("stay"):
        interview.step = "done" if result["done"] else STEP_ORDER[STEP_ORDER.index(step) + 1]

    return result


# ---------------------------------------------------------------------------
# Part 5: planning chat -> editable brief
# ---------------------------------------------------------------------------

# Part 5: transcript -> editable brief, ONE cheap guided_json call
# (role="chat": no thinking, non-streaming — same tier as chat.suggestions,
# and for the same reason: a short synchronous summarization on the request
# path, well inside the Cloudflare edge cap). Tutor-editable via the registry
# (interview.planning_distill); {language} and {transcript} are filled by
# distill_planning_brief — the tutor's edit is the TEMPLATE, same contract as
# chat.suggestions.
DISTILL_SYSTEM = (
    "You read a planning conversation between a guitar TUTOR and an "
    "assistant about a course the tutor wants to create. Distill what the "
    "TUTOR actually wants into a brief IN {language}, written as if the "
    "tutor wrote it himself, structured as short lines under these headers: "
    "goals, topics to cover, emphasis/priorities, teaching preferences, "
    "things to avoid. Keep ONLY conclusions the tutor stated or clearly "
    "agreed to — dead ends and rejected ideas stay out. No preamble, no "
    "commentary; return ONLY the JSON the schema describes.\n\n"
    "THE CONVERSATION:\n{transcript}"
)
DISTILL_SLICE_ID = "interview.planning_distill"

DISTILL_SCHEMA = {
    "type": "object",
    "properties": {"brief": {"type": "string"}},
    "required": ["brief"],
    "additionalProperties": False,
}


def distill_planning_brief(db: Session, interview: CurriculumInterview) -> str:
    """The planning chat's exit: transcript in, tutor-voiced brief out.
    Raises ValueError when there is nothing to distill (no bound session or
    no user turns) — the router maps that to a 409 the UI can explain."""
    from app.models.chat import ChatSession, Message  # local: avoid cycles if any

    session = db.scalars(
        select(ChatSession)
        .where(ChatSession.interview_id == interview.id)
        .order_by(ChatSession.created_at.desc())
    ).first()
    if session is None:
        raise ValueError("no planning chat session for this interview")
    messages = db.scalars(
        select(Message).where(Message.session_id == session.id).order_by(Message.created_at)
    ).all()
    visible = [m for m in messages if m.role in ("user", "assistant") and (m.content or "").strip()]
    if not any(m.role == "user" for m in visible):
        raise ValueError("planning chat has no tutor turns to distill")

    transcript = "\n".join(f"{m.role.upper()}: {m.content.strip()}" for m in visible)
    who = (interview.answers or {}).get("who") or {}
    language = "Greek" if (who.get("language") or "el") == "el" else "English"

    prompt = resolve(db, DISTILL_SLICE_ID, DISTILL_SYSTEM).format(
        language=language, transcript=transcript,
    )
    result = get_provider().guided_json(
        [{"role": "user", "content": prompt}], DISTILL_SCHEMA, role="chat",
    )
    return (result.get("brief") or "").strip()
